### ISSUE TITLE
Webpack encounters errors without manually installing some modules

### ISSUE THREAD

**Issue by carbureted** [nkbt/react-text-filter#10]
I get errors in the pattern below for the following modules - 'redbox-react', 'react-transform-catch-errors', 'react-transform-hmr'. I notice several are in dev dependencies but not the primary dependencies.

`ERROR in ./~/react-text-filter/lib/TextFilter.js
Module not found: Error: Cannot resolve module 'redbox-react'`

Also, once I install all of the above dependencies, I get the following error - `Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr`

Thanks!

**Comment by nkbt** [comment]
Hi, @carbureted 

They should not be in main dependencies since are needed only for development.

If you are using library in your project (as `require('react-text-filter')`) - it has all pre-built files in there. As well as original `src` in case you wish to build yourself.

**Comment by nkbt** [comment]
Closing for now, reopen please, if you still have an issue
