### ISSUE TITLE
Feature request: controlled input or option to clear

### ISSUE THREAD

**Issue by thienanle** [nkbt/react-text-filter#28]
Afaik, currently the component is uncontrolled so there is no way to set the value programmatically. I think having a clear button would be useful and would follow common UX patterns.

**Comment by nkbt** [comment]
It passes through all the props to https://github.com/nkbt/react-debounce-input (which is used as backend). So it should be totally controllable.

Alternatively you can just use `react-debounce-input` and customize it in any way you need =)
