### ISSUE TITLE
Document that TextFilter properties are passed to <input> tag

### ISSUE THREAD

**Issue by rutsky** [nkbt/react-text-filter#6]
It's not obvious from documentation that to change placeholder text it's enough to add "placeholder" property to TextFilter:

```
<TextFilter placeholder="Item Name" onFilter={...} />
```

**Comment by nkbt** [comment]
Thanks. Did I mentioned, that all props will be applied to the input? Need
to doublecheck. And add some examples for this for sure

**Comment by rutsky** [comment]
> Did I mentioned, that all props will be applied to the input?
No, you didn't. I learned that from the source code.

By the way, thanks for sharing this React component!

**Comment by nkbt** [comment]
:+1:

Btw, published today react-debounce-input which will be used as core for
this one.
